// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpalaAPIPam.Data;

#nullable disable

namespace OpalaAPIPam.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OpalaAPIPam.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Nota")
                        .HasColumnType("float");

                    b.Property<int>("usuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("usuarioId");

                    b.ToTable("Avaliacao");
                });

            modelBuilder.Entity("OpalaAPIPam.Models.Banda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("estilo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeBanda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("usuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("usuarioId");

                    b.ToTable("Banda");
                });

            modelBuilder.Entity("OpalaAPIPam.Models.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Dt_Apresentacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Dt_Cont")
                        .HasColumnType("datetime2");

                    b.Property<int>("duracao")
                        .HasColumnType("int");

                    b.Property<int>("usuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("usuarioId");

                    b.ToTable("Contrato");
                });

            modelBuilder.Entity("OpalaAPIPam.Models.Instrumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("usuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("usuarioId");

                    b.ToTable("Instrumento");
                });

            modelBuilder.Entity("OpalaAPIPam.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Telefone")
                        .HasColumnType("bigint");

                    b.Property<int>("generoEnum")
                        .HasColumnType("int");

                    b.Property<int>("tipoEnum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "PedroS@gmail.com",
                            Endereco = "",
                            Nome = "Pedro Silva",
                            Senha = "pedrinho123",
                            generoEnum = 0,
                            tipoEnum = 0
                        },
                        new
                        {
                            Id = 2,
                            Email = "gHenrique@gmail.com",
                            Endereco = "",
                            Nome = "Gustavo Henrique",
                            Senha = "henrique123",
                            generoEnum = 0,
                            tipoEnum = 0
                        });
                });

            modelBuilder.Entity("OpalaAPIPam.Models.Avaliacao", b =>
                {
                    b.HasOne("OpalaAPIPam.Models.Usuario", "usuario")
                        .WithMany("avaliacoes")
                        .HasForeignKey("usuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("OpalaAPIPam.Models.Banda", b =>
                {
                    b.HasOne("OpalaAPIPam.Models.Usuario", "usuario")
                        .WithMany("banda")
                        .HasForeignKey("usuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("OpalaAPIPam.Models.Contrato", b =>
                {
                    b.HasOne("OpalaAPIPam.Models.Usuario", "usuario")
                        .WithMany("contrato")
                        .HasForeignKey("usuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("OpalaAPIPam.Models.Instrumento", b =>
                {
                    b.HasOne("OpalaAPIPam.Models.Usuario", "usuario")
                        .WithMany("instrumento")
                        .HasForeignKey("usuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("OpalaAPIPam.Models.Usuario", b =>
                {
                    b.Navigation("avaliacoes");

                    b.Navigation("banda");

                    b.Navigation("contrato");

                    b.Navigation("instrumento");
                });
#pragma warning restore 612, 618
        }
    }
}
